version: '3.8'

services:
  authentication-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthenticationDB1;User Id=sa;Password=${SQL_SA_PASSWORD}

  hello2:
    build: .
    ports:
      - "5123:5123"
      - "7037:7037"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5123;http://0.0.0.0:7037
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
